const Alert = require('../models/Alert');
const User = require('../models/User');
const Incident = require('../models/Incident');
const Notification = require('../models/Notification');
const AwarenessContent = require('../models/awareness/AwarenessContent');
const { sendBulkWhatsAppAlerts } = require('./whatsappService');

const AWARENESS_GUIDELINE_LIMIT = 2;

function dedupeAwarenessItems(items = []) {
  const seen = new Set();
  return items.filter((item) => {
    const id = item?._id?.toString?.() || item?._id || item?.id;
    const contentKey = `${(item?.title || '').trim().toLowerCase()}|${(item?.content || '').trim().toLowerCase()}`;
    const key = id || contentKey;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

class SmartAlertService {

  // Auto-generate alerts based on incident severity
  static async createIncidentAlert(incident) {
    try {
      let priority = 'MEDIUM';
      let category = 'WARNING';
      let targetRoles = ['OFFICER'];

      // Determine alert priority and category based on incident
      if (incident.priority === 'HIGH' || incident.priority === 'CRITICAL') {
        priority = 'URGENT';
        category = 'EMERGENCY';
        targetRoles = ['OFFICER', 'ADMIN'];
      } else if (incident.priority === 'MEDIUM') {
        priority = 'HIGH';
        category = 'WARNING';
      }

      // Build GeoJSON location from incident's lat/lng
      let alertLocation = undefined;
      if (incident.location && incident.location.lat != null && incident.location.lng != null) {
        alertLocation = {
          type: 'Point',
          coordinates: [incident.location.lng, incident.location.lat]
        };
      }

      const alert = await Alert.create({
        title: `New ${incident.priority} Incident: ${incident.category}`,
        message: `A ${(incident.priority || '').toLowerCase()} priority ${(incident.category || '').toLowerCase()} incident has been reported. ${incident.description ? incident.description.substring(0, 200) + '...' : ''}`,
        category,
        priority,
        createdBy: incident.reporterId,
        targetRoles,
        relatedIncident: incident._id,
        location: alertLocation
      });

      // Also send geo-alert notifications + awareness
      await SmartAlertService.handleNewAlert(alert);

      return alert;
    } catch (error) {
      console.error('Error creating incident alert:', error);
      throw error;
    }
  }

  // Create weather-based alerts
  static async createWeatherAlert(weatherData) {
    try {
      const { type, severity, location, description, expiresAt } = weatherData;

      let priority = 'LOW';
      let category = 'INFO';
      let targetRoles = ['CITIZEN', 'OFFICER'];

      if (severity === 'severe' || severity === 'extreme') {
        priority = 'URGENT';
        category = 'EMERGENCY';
        targetRoles = ['CITIZEN', 'OFFICER', 'ADMIN'];
      } else if (severity === 'moderate') {
        priority = 'MEDIUM';
        category = 'WARNING';
      }

      const alert = await Alert.create({
        title: `Weather Alert: ${type}`,
        message: description || `${severity} ${type} conditions expected in your area.`,
        category,
        priority,
        createdBy: null, // System-generated
        targetRoles,
        location,
        expiresAt: expiresAt || new Date(Date.now() + 24 * 60 * 60 * 1000) // 24 hours default
      });

      // Trigger geo-alert notifications + awareness
      await SmartAlertService.handleNewAlert(alert);

      return alert;
    } catch (error) {
      console.error('Error creating weather alert:', error);
      throw error;
    }
  }

  // Create geofenced alerts for users entering/leaving areas
  static async createGeofenceAlert(userId, area, action) {
    try {
      const user = await User.findById(userId);
      if (!user || user.status !== 'ACTIVE') {
        return null;
      }

      const message = action === 'enter'
        ? `You have entered ${area.name}. ${area.alertMessage || ''}`
        : `You have left ${area.name}. ${area.exitMessage || ''}`;

      const alert = await Alert.create({
        title: `Area ${action === 'enter' ? 'Entry' : 'Exit'}: ${area.name}`,
        message,
        category: area.alertCategory || 'INFO',
        priority: area.alertPriority || 'LOW',
        createdBy: null, // System-generated
        targetRoles: [user.role],
        location: area.location
      });

      // Also create a direct notification for the specific user
      await Notification.create({
        userId,
        title: alert.title,
        message: alert.message,
        type: 'geo-alert',
        priority: alert.priority,
        metadata: {
          alertId: alert._id,
          areaName: area.name,
          action,
          autoGenerated: true
        }
      });

      return alert;
    } catch (error) {
      console.error('Error creating geofence alert:', error);
      throw error;
    }
  }

  // Send scheduled alerts
  static async createScheduledAlert(scheduleData) {
    try {
      const {
        title,
        message,
        category,
        priority,
        targetRoles,
        scheduledBy,
        expiresAt
      } = scheduleData;

      // Validate that target users exist
      const targetRolesArray = targetRoles && targetRoles.length > 0
        ? targetRoles
        : ['CITIZEN', 'OFFICER'];

      const userCount = await User.countDocuments({
        role: { $in: targetRolesArray },
        status: 'ACTIVE'
      });

      if (userCount === 0) {
        return null;
      }

      const alert = await Alert.create({
        title,
        message,
        category: category || 'INFO',
        priority: priority || 'MEDIUM',
        createdBy: scheduledBy,
        targetRoles: targetRolesArray,
        expiresAt
      });

      return alert;
    } catch (error) {
      console.error('Error creating scheduled alert:', error);
      throw error;
    }
  }

  // Clean up expired alerts
  static async cleanupExpiredAlerts() {
    try {
      const result = await Alert.updateMany(
        {
          isActive: true,
          expiresAt: { $lt: new Date() }
        },
        {
          isActive: false
        }
      );

      console.log(`Deactivated ${result.modifiedCount} expired alerts`);
      return result.modifiedCount;
    } catch (error) {
      console.error('Error cleaning up expired alerts:', error);
      throw error;
    }
  }

  // Get alert analytics
  static async getAlertAnalytics(startDate, endDate) {
    try {
      const match = {
        createdAt: {
          $gte: startDate || new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days default
          $lte: endDate || new Date()
        }
      };

      const [
        totalAlerts,
        alertsByCategory,
        alertsByPriority,
        alertsByHour
      ] = await Promise.all([
        Alert.countDocuments(match),

        Alert.aggregate([
          { $match: match },
          { $group: { _id: '$category', count: { $sum: 1 } } }
        ]),

        Alert.aggregate([
          { $match: match },
          { $group: { _id: '$priority', count: { $sum: 1 } } }
        ]),

        Alert.aggregate([
          { $match: match },
          {
            $group: {
              _id: { $hour: '$createdAt' },
              count: { $sum: 1 }
            }
          },
          { $sort: { '_id': 1 } }
        ])
      ]);

      return {
        totalAlerts,
        alertsByCategory: alertsByCategory.reduce((acc, item) => {
          acc[item._id] = item.count;
          return acc;
        }, {}),
        alertsByPriority: alertsByPriority.reduce((acc, item) => {
          acc[item._id] = item.count;
          return acc;
        }, {}),
        alertsByHour: alertsByHour.reduce((acc, item) => {
          acc[item._id] = item.count;
          return acc;
        }, {})
      };
    } catch (error) {
      console.error('Error getting alert analytics:', error);
      throw error;
    }
  }

  // -------------------------------------------------------
  // Integration entry-point: called whenever a new alert is
  // created. Finds affected users nearby and fires geo-alert
  // notifications, attaching relevant awareness content.
  //
  // alertData shape (from Alert model):
  //   { _id, title, category, location: { type:'Point', coordinates:[lng,lat] } }
  // radiusKm defaults to 5 km.
  // -------------------------------------------------------
  static async handleNewAlert(alertData, radiusKm = 5) {
    try {
      const radiusMeters = radiusKm * 1000;

      // 1. Find users who have a location within the radius
      //    Fall back to all ACTIVE users if no location is set on the alert.
      let nearbyUsers = [];

      if (
        alertData.location &&
        alertData.location.coordinates &&
        alertData.location.coordinates.length === 2
      ) {
        try {
          nearbyUsers = await User.find({
            status: 'ACTIVE',
            role: { $in: alertData.targetRoles || ['CITIZEN', 'OFFICER'] },
            location: {
              $near: {
                $geometry: {
                  type: 'Point',
                  coordinates: alertData.location.coordinates
                },
                $maxDistance: radiusMeters
              }
            }
          }).select('_id');
        } catch (geoErr) {
          // If geo query fails (e.g. no 2dsphere index on users), fall back
          console.warn('[handleNewAlert] Geo query failed, falling back to role-based:', geoErr.message);
          nearbyUsers = [];
        }
      }

      // Fall back: notify all active citizens and officers
      if (nearbyUsers.length === 0) {
        nearbyUsers = await User.find({
          status: 'ACTIVE',
          role: { $in: alertData.targetRoles || ['CITIZEN', 'OFFICER'] }
        }).select('_id');
      }

      if (nearbyUsers.length === 0) {
        console.log(`[handleNewAlert] No target users found for alert: ${alertData._id}`);
        return { notified: 0, awarenessAttached: 0 };
      }

      // 2. Find relevant awareness content based on alert category
      //    Map alert categories to awareness triggers
      const categoryToTrigger = {
        EMERGENCY: 'fire',
        WARNING: 'poaching',
        INFO: 'general',
        ANNOUNCEMENT: 'general'
      };
      const trigger = alertData.alertType || categoryToTrigger[alertData.category] || 'general';

      const awarenessQuery = {
        isActive: true
      };

      if (Array.isArray(alertData.relatedAwareness) && alertData.relatedAwareness.length > 0) {
        awarenessQuery._id = { $in: alertData.relatedAwareness };
      } else {
        awarenessQuery.triggers = trigger;
      }

      let relevantAwareness = await AwarenessContent.find(awarenessQuery)
        .select('_id title content category')
        .limit(10);

      relevantAwareness = dedupeAwarenessItems(relevantAwareness).slice(0, AWARENESS_GUIDELINE_LIMIT);

      // 3. Build notification documents — one per nearby user
      const notifications = nearbyUsers.map(user => ({
        userId: user._id,
        title: `🚨 Alert: ${alertData.title}`,
        message: alertData.message || `A new ${(alertData.category || 'safety').toLowerCase()} alert has been issued. Please check safety guidelines.`,
        type: 'geo-alert',
        priority: alertData.priority || 'HIGH',
        metadata: {
          alertId: alertData._id,
          alertCategory: alertData.category,
          alertType: trigger,
          awarenessIds: relevantAwareness.map(a => a._id),
          awarenessItems: relevantAwareness.map(a => ({ id: a._id, title: a.title, category: a.category })),
          autoGenerated: true
        }
      }));

      // 4. Bulk insert for efficiency
      await Notification.insertMany(notifications);

      console.log(
        `[handleNewAlert] Sent ${notifications.length} geo-alert notifications` +
        ` (${relevantAwareness.length} awareness items attached)`
      );

      // 5. Send WhatsApp alerts via UltraMsg to nearby users who have a phone number
      const usersWithPhone = await User.find({
        _id: { $in: nearbyUsers.map(u => u._id) },
        phone: { $exists: true, $ne: '' },
        status: 'ACTIVE'
      }).select('phone name');

      if (usersWithPhone.length > 0) {
        // Await so the result (including recipients list) flows back to the controller
        const whatsappResult = await sendBulkWhatsAppAlerts(
          usersWithPhone,
          alertData.title,
          alertData.message,
          alertData.category,
          relevantAwareness
        ).catch(err => {
          console.error('[handleNewAlert] WhatsApp dispatch error:', err);
          return { sent: 0, failed: 0, total: 0, recipients: [] };
        });

        return {
          notified: notifications.length,
          awarenessAttached: relevantAwareness.length,
          whatsapp: whatsappResult
        };
      }

      return {
        notified: notifications.length,
        awarenessAttached: relevantAwareness.length,
        whatsapp: { sent: 0, failed: 0, total: 0, recipients: [] }
      };
    } catch (error) {
      console.error('Error in handleNewAlert:', error);
      throw error;
    }
  }

  // Send bulk alerts efficiently
  static async sendBulkAlerts(alertsData) {
    try {
      const alerts = await Alert.insertMany(alertsData);
      return alerts;
    } catch (error) {
      console.error('Error sending bulk alerts:', error);
      throw error;
    }
  }
}

module.exports = SmartAlertService;
